#include <signal.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>

#include <setjmp.h>

jmp_buf jmp1;
int a = 0;

void handler() {
  printf("SIGFPE handled (a = %d).\n", a);
  siglongjmp(jmp1, 1); //if you comment this, the program gets stuck in a "a = 10 / a"; =>  handler() loop
}

int main() {
  int i = 0;

  signal(SIGFPE, handler);

  if( sigsetjmp(jmp1, 1) == 0 )
  {
    a = 10 / a;
  }
  printf("returned from SIGFPE handler.\n");

/*
 From man sigaction(2):
 
   According to POSIX, the behavior of a process is undefined after it
   ignores a SIGFPE, SIGILL, or SIGSEGV signal that was not generated by
   kill(2) or raise(3).  Integer division by zero has undefined result.
   On some architectures it will generate a SIGFPE signal.
   Ignoring this signal might lead to an endless loop.
*/        
       
	if(signal(SIGFPE,SIG_IGN)==SIG_ERR)
    perror("signal(SIGFPE)");

  struct sigaction act;
  act.sa_handler = SIG_IGN;
  act.sa_flags = 0; 
  sigemptyset(&(act.sa_mask));
  if(sigaction(SIGFPE, &act, NULL)==-1)
    perror("sigaction(SIGFPE)");
  
	while(1) {
		fprintf(stderr, "i = %d\n", i++);    
    a = 10 / a;
	}
  
  
}
